### ISSUE TITLE
Agenda height adjustment

### ISSUE THREAD

**Issue by luisdmartinezc** [Revln9/react-agenda#12]
Is there a way to adjust the height for the body of the agenda when calling the component? Specifically, I'm looking to change the height property for the css class .agenda__table.\--body . Thanks!

**Comment by Revln9** [comment]
Well not for the moment, this plugin is almost deprecated. it had no updates for like years, you can always overwrite the css rule 

```
.agenda__table.\--body {
  height: calc(100vh - 64px) ! important;  /*adjust the height by changing the 100vh*/
  overflow: overlay;
  -webkit-transform: translateZ(0);
 }
```

I started to rewrite this component like a year ago, without using any framework, but didn't finish it because my full time job is very time consuming. But i plan to finish it this summer.
