### ISSUE TITLE
using dependecy "drag-drop-touch-polyfill"  from NPM repo instead GIT

### ISSUE THREAD

**Issue by NorbertSzabo** [Revln9/react-agenda#5]
Hello, 
could you please use the "drag-drop-touch-polyfill" version from npm instead of git?  
e.g. "drag-drop-touch-polyfill": "^1.0.0", instead 
      "drag-drop-touch-polyfill": "https://github.com/Revln9/drag-drop-touch-polyfill-ES5-compiled.git",
Many thx.

**Comment by Revln9** [comment]
Hi Norbert , 
Unfortunately i can't use the 'original' repo of this module , because it fails to compile with some popular compilers (webpack...etc ) 
I'm planning to make a complete rewrite of this module and publish it separately on npm. But it takes quite some time to do it , and i don't really have it for now.
If you have an issue with it , post the error , so we can help otherwise , i hope it helps .
